repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: [--unsafe] # Required due to custom constructors (e.g. !ENV)
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.5.1
    hooks:
      - id: python-check-blanket-noqa
  - repo: local
    hooks:
      - id: flake8
        name: Flake8
        description: This hook runs flake8 within our project's poetry environment.
        entry: poetry run flake8
        language: system
        types: [python]
        exclude: ^(tests|example)/*
        require_serial: true
      - id: docrunner
        name: Docrunner
        description: This hook runs docrunner within our project's root directory, targeting docs/docs.
        entry: poetry run docrunner run
        language: system
        pass_filenames: false
        require_serial: true
